#! /bin/sh
if [[ "${PRIMARY_MONITOR}" == "${SECONDARY_MONITOR}" ]]; then
    bspc monitor "${PRIMARY_MONITOR}" -d 1 2 3 4 5 6 7 8 9 10
else
    bspc monitor "${PRIMARY_MONITOR}" -d 1 2 3 4 5
    bspc monitor "${SECONDARY_MONITOR}" -d 6 7 8 9 10
fi

bspc config border_width 2
bspc config window_gap 10

bspc config active_border_color "${COLORS_BASE02}"
bspc config focused_border_color "${COLORS_BASE03}"
bspc config normal_border_color "${COLORS_BASE00}"

bspc config click_to_focus true
bspc config split_ratio 0.5

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config focus_by_distance true

bspc rule -a Steam desktop=^1
bspc rule -a discord desktop=^1
bspc rule -a Termite desktop=^2
bspc rule -a URxvt desktop=^2
bspc rule -a Subl3 desktop=^3
bspc rule -a jetbrains-phpstorm desktop=^3
bspc rule -a Slack desktop=^4
bspc rule -a csgo_linux64 desktop=^5 state=fullscreen
bspc rule -a Chromium desktop=^6
bspc rule -a Firefox desktop=^6
bspc rule -a Waterfox desktop=^6
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a KeePass2 state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb -merge ~/.Xresources &
~/.fehbg &
~/.config/polybar/start.sh &
