#! /bin/sh
bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 10

bspc config active_border_color \#383838
bspc config focused_border_color \#585858
bspc config normal_border_color \#181818

bspc config click_to_focus true
bspc config split_ratio 0.5

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config focus_by_distance true

bspc rule -a Steam desktop=^1
bspc rule -a discord desktop=^1
bspc rule -a Termite desktop=^2
bspc rule -a URxvt desktop=^2
bspc rule -a Subl3 desktop=^3
bspc rule -a csgo_linux64 desktop=^5 state=fullscreen
bspc rule -a Chromium desktop=^6
bspc rule -a Firefox desktop=^6
bspc rule -a Waterfox desktop=^6
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a KeePass2 state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb -merge ~/.Xresources &
~/.fehbg &
~/.config/polybar/start.sh &
