#!/bin/zsh
pac=$(checkupdates|wc -l)
aur=$(yay -Qum|wc -l)
check=$((pac + aur))
regex='^[0-9]+$'

if [[ $pac =~ $regex && $aur =~ $regex && ("$pac" != "0" || "$aur" != "0") ]]; then
    echo "$pac $aur"
fi
