#!/bin/bash
case "${HOSTNAME}" in
    'arch-home')
        bspc monitor DP-4 -d home term code data chat music vm rand
        bspc monitor DP-2 -d game
        ;;
    'arch-adcalls')
        bspc monitor HDMI-1 -d home data chat music
        bspc monitor DVI-D-1 -d code term game vm rand
        ;;
esac

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color $(xrdb -query|grep 'color5:'|cut -f2)
bspc config focused_border_color $(xrdb -query|grep 'color1:'|cut -f2)
bspc config normal_border_color $(xrdb -query|grep 'color8:'|cut -f2)
bspc config presel_feedback_color $(xrdb -query|grep 'color2:'|cut -f2)

bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config swallow_first_click true
bspc config split_ratio 0.5

bspc rule -a Chromium desktop='home'
bspc rule -a qutebrowser desktop='home'
bspc rule -a firefox desktop='home'
bspc rule -a discord desktop='home'
bspc rule -a Termite desktop='term'
bspc rule -a Code desktop='code'
bspc rule -a Subl3 desktop='code'
bspc rule -a jetbrains-phpstorm desktop='code'
bspc rule -a DBeaver desktop='data'
bspc rule -a Postman desktop='data'
bspc rule -a discord desktop='chat'
bspc rule -a Slack desktop='chat'
bspc rule -a Spotify desktop='music'
bspc rule -a Steam desktop='game'
bspc rule -a csgo_linux64 desktop='game' state=fullscreen
bspc rule -a Virt-manager desktop='vm'
bspc rule -a Galculator state=floating
bspc rule -a feh state=floating
bspc rule -a KeePass2 state=floating
bspc rule -a Oblogout state=fullscreen sticky=true monitor=primary
case "${HOSTNAME}" in
    'arch-home')
        bspc rule -a looking-glass-client state=floating rectangle=1920x1080+320+180
        bspc rule -a scratchpad state=floating hidden=true sticky=true rectangle=1260x720+650+360
        bspc rule -a Slack state=floating sticky=true rectangle=1260x720+650+360
        bspc rule -a Pavucontrol state=floating rectangle=1260x720+650+360
        ;;
    'arch-adcalls')
        bspc rule -a scratchpad state=floating hidden=true sticky=true rectangle=1260x720+330+180
        bspc rule -a Slack state=floating sticky=true rectangle=1260x720+330+180
        bspc rule -a Pavucontrol state=floating rectangle=1260x720+330+180
        ;;
esac


feh --bg-fill --no-fehbg ~/.background &

wmname LG3D &

~/.config/polybar/launch.sh &

if ! pgrep -ax termite | grep '\-\-class scratchpad'; then
    termite --class scratchpad -t Scratchpad -e ~/.config/bspwm/scratch &
fi
