#!/bin/bash
bspc monitor "${MONITORS_PRIMARY}" -d 1

bspc config border_width 0
bspc config window_gap 0
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color "${COLORS_BASE02}"
bspc config focused_border_color "${COLORS_BASE03}"
bspc config normal_border_color "${COLORS_BASE00}"

bspc config click_to_focus true
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle false
bspc config focus_by_distance true
