#!/bin/bash
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color $(xrdb -query|grep 'color19:'|cut -f2)
bspc config focused_border_color $(xrdb -query|grep 'color8:'|cut -f2)
bspc config normal_border_color $(xrdb -query|grep 'color0:'|cut -f2)
bspc config presel_feedback_color $(xrdb -query|grep 'color2:'|cut -f2)

bspc config initial_polarity second_child
bspc config click_to_focus true
bspc config split_ratio 0.5

bspc rule -a Chromium desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Firefox desktop='^1'
bspc rule -a discord desktop='^1'
bspc rule -a Termite desktop='^2'
bspc rule -a Subl3 desktop='^3'
bspc rule -a jetbrains-phpstorm desktop='^3'
bspc rule -a DBeaver desktop='^4'
bspc rule -a Slack desktop=^'5'
bspc rule -a Virt-manager desktop='^8'
bspc rule -a Steam desktop='^9'
bspc rule -a csgo_linux64 desktop='^9' state=fullscreen
bspc rule -a Spotify desktop='^9'
bspc rule -a KeePass2 state=floating
bspc rule -a scratchpad state=floating hidden=on sticky=on

wmname LG3D &

if ! pgrep -x compton; then
    compton -b &
fi

feh --bg-fill --no-fehbg ~/.background &

if ! pgrep -x caffeine; then
    caffeine &
fi

if ! pgrep -x redshift; then
    redshift &
fi

if ! pgrep -x sxhkd; then
    sxhkd &
else
    pkill -USR1 -x sxhkd &
fi

~/.config/polybar/launch.sh &

if [ ! -f /tmp/scratchid ]; then
    termite --class scratchpad -t scratchpad -e ~/.config/bspwm/scratch &
fi
