#!/bin/zsh
case "${HOST}" in
    "arch-home")
        bspc monitor DisplayPort-1 -d web data chat music vm
        bspc monitor DisplayPort-0 -d code term game rand
        RECT="1260x720+650+360"
        ;;
    "arch-adcalls")
        bspc monitor DVI-D-1 -d web data chat music
        bspc monitor DP-1 -d code term game vm rand
        RECT="1260x720+330:180"
        ;;
esac

# Source pywal colors
. ~/.cache/wal/colors.sh

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color "$color6"
bspc config focused_border_color "$color4"
bspc config normal_border_color "$color8"
bspc config presel_feedback_color "$color2"

bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config split_ratio 0.5

bspc config external_rules_command ~/.config/bspwm/external-rules

bspc rule -a Chromium desktop="web"
bspc rule -a firefox desktop="web"
bspc rule -a discord desktop="web"
bspc rule -a DBeaver desktop="data"
bspc rule -a Filezilla desktop="data"
bspc rule -a Postman desktop="data"
bspc rule -a Thunar desktop="data"
bspc rule -a discord desktop="chat"
bspc rule -a Slack desktop="chat" state=floating rectangle=${RECT}
bspc rule -a Element desktop="chat" state=floating rectangle=${RECT}
bspc rule -a Spotify desktop="music"
bspc rule -a Virt-manager desktop="vm"
bspc rule -a Code desktop="code"
bspc rule -a Godot desktop="code"
bspc rule -a jetbrains-phpstorm desktop="code"
bspc rule -a Alacritty desktop="term"
bspc rule -a battle.net.exe desktop="game"
bspc rule -a Steam desktop="game"
bspc rule -a csgo_linux64 desktop="game" state=fullscreen
bspc rule -a projectascension desktop="game"
bspc rule -a parsecd desktop="game"
bspc rule -a feh state=floating
bspc rule -a GLava layer=below state=fullscreen sticky=on
bspc rule -a KeePass2 state=floating
bspc rule -a mpv state=floating rectangle=${RECT}
bspc rule -a Pavucontrol state=floating rectangle=${RECT}
bspc rule -a htop state=floating rectangle=${RECT}
bspc rule -a scratchpad state=floating marked=on rectangle=${RECT}
bspc rule -a update-pkgs state=floating rectangle=${RECT}

wmname LG3D &

~/.config/polybar/launch &
