#!/bin/zsh
RECT="1920x1080+0+0"

# Source pywal colors
. ~/.cache/wal/colors.sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color "$color6"
bspc config focused_border_color "$color4"
bspc config normal_border_color "$color8"
bspc config presel_feedback_color "$color2"

bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config split_ratio 0.5

bspc config external_rules_command ~/.config/bspwm/external-rules

bspc rule -a Chromium desktop="web"
bspc rule -a firefox desktop="web"
bspc rule -a discord desktop="web"
bspc rule -a DBeaver desktop="data"
bspc rule -a FileZilla desktop="data"
bspc rule -a Postman desktop="data"
bspc rule -a Thunar desktop="data"
bspc rule -a discord desktop="chat"
bspc rule -a Slack state=floating rectangle=${RECT} center=true
bspc rule -a Element desktop="chat" state=floating rectangle=${RECT} center=true
bspc rule -a Spotify desktop="music"
bspc rule -a Virt-manager desktop="vm"
bspc rule -a Code desktop="code"
bspc rule -a Godot desktop="code"
bspc rule -a jetbrains-phpstorm desktop="code"
bspc rule -a Alacritty desktop="term"
bspc rule -a battle.net.exe desktop="game"
bspc rule -a Steam desktop="game"
bspc rule -a csgo_linux64 desktop="game" state=fullscreen
bspc rule -a projectascension desktop="game"
bspc rule -a parsecd desktop="game"
bspc rule -a feh state=floating
bspc rule -a GLava layer=below state=fullscreen sticky=on
bspc rule -a KeePass2 state=floating
bspc rule -a mpv state=floating rectangle=${RECT} center=true
bspc rule -a Pavucontrol state=floating rectangle=${RECT} center=true
bspc rule -a htop state=floating rectangle=${RECT} center=true
bspc rule -a io.elementary.calculator state=floating
bspc rule -a scratchpad state=floating marked=on rectangle=${RECT} center=true
bspc rule -a update-pkgs state=floating rectangle=${RECT} center=true

wmname LG3D &

~/.config/polybar/launch &
